### ISSUE TITLE
the thing doesnt even boot

### ISSUE THREAD

**Issue by D0nnieD4rk0** [xdevs23/linux-nitrous#1]
probably a generic version that my hardware cant support
add different versions for those
installed from ur repo btw

**Comment by xdevs23** [comment]
Sorry, I don't support other versions. The binary distributions and the default config are specifically made to compile for haswell, on purpose. If you need a different version, run `USE_MPERFORMANCE=true makepkg -si` to compile specifically for your machine. Alternatively, change the CPU in the config.
