### ISSUE TITLE
Compatibility with `hid-nx-dkms`

### ISSUE THREAD

**Issue by Impeta** [xdevs23/linux-nitrous#3]
It seems your own kernel has trouble to support and install the module [hid-nx-dkms](https://github.com/emilyst/hid-nx-dkms). Think you could get around on it?
[
For more information, here.](https://github.com/emilyst/hid-nx-dkms/issues/12)

**Comment by xdevs23** [comment]
Thank you for reporting. I'll take a look at this and let you know soon.

**Comment by xdevs23** [comment]
I looked at it and the header `generated/autoconf.h` exists in both linux-nitrous-headers and linux-headers.
The exact path would be `/usr/lib/modules/<kernel name>/build/include/generated/autoconf.h`.

**Comment by xdevs23** [comment]
Is this still an issue?
